version: 0.2
phases:

  build:
    run-as: root
    on-failure: ABORT |
    commands:
      - docker build -t 032401129069.dkr.ecr.ca-central-1.amazonaws.com/jhub-open-userimage:latest .
      - aws ecr get-login-password --profile saml --region ca-central-1 | docker login --username AWS --password-stdin 032401129069.dkr.ecr.ca-central-1.amazonaws.com
